### ISSUE TITLE
test for NRPyEllipticET is very slow

### ISSUE THREAD

**Issue by rhaas80** [assumpcaothiago/NRPyElliptic#1]
No actual bug but mostly that it wold be good if the test could be sped up. Right now, `NRPyEllipticET_test_conformally_flat_BBH` is the [slowest test](https://einsteintoolkit.github.io/tests/), by a significant marging (almost 3 times slower than the next slower test). With 339 tests in the ET one tries to encourage each test to run as quickly as possible (https://docs.einsteintoolkit.org/et-docs/Adding_a_test_case).

**Comment by assumpcaothiago** [comment]
Issue fixed in https://github.com/assumpcaothiago/NRPyElliptic/commit/8f825f9be7bc1f34b24782403235059c9248faf2 thanks to Leo Werneck.
